# Site settings
title: Lore Wine & Spirits
email: info@lorewine.com
url: https://example.github.io
baseurl: /lore
description: "Lore Wine & Spirits is a preeminent wine retailer located in the Freedom Tower in New York. Lore specializes in providing our customers with the best wines for their palate at a reasonable price."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Lore Wine & Spirits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

# Sass settings
sass:
    sass_dir: _sass
