# Site settings
title: Pure Liquid Wine & Spirits
email: info@drinkpl.com
url: http://drinklore.com
description: "Pure Liquid Wine & Spirits is the preeminent wine retailer located in the Freedom Tower in New York. Pure Liquid specializes in providing our customers with the best wines for their palate at a reasonable price."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#b98250'

# Footer settings
footer: Pure Liquid Wine & Spirits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty

# Sass settings
sass:
    sass_dir: _sass
